src/Entity/Element.php
<?php

namespace Tigris\ContentBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Tigris\BaseBundle\Entity\Model\User;
use Tigris\ContentBundle\Entity\Translation\ElementTranslation;
use Tigris\ContentBundle\Repository\ElementRepository;

#[ORM\Entity(repositoryClass: ElementRepository::class)]
#[ORM\Table(name: 'content_element')]
#[Gedmo\SoftDeleteable(fieldName: 'deletedAt', timeAware: false, hardDelete: true)]
#[Gedmo\Loggable]
#[Gedmo\TranslationEntity(class: ElementTranslation::class)]
class Element implements \Stringable
{
    use SoftDeleteableEntity;
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int|null $id = null;

    #[ORM\Column(length: 150)]
    #[Gedmo\Translatable]
    #[Gedmo\Versioned]
    private string $name;

    #[ORM\Column]
    private bool $public = false;

    #[ORM\Column]
    private bool $draft = false;

    #[ORM\Column(unique: true)]
    #[Gedmo\Translatable]
    #[Gedmo\Slug(fields: ['createdAt', 'name'], updatable: true)]
    private string $slug;

    #[Gedmo\Locale]
    private string|null $locale = null;

    #[ORM\Column(length: 180)]
    private string $type;

    private string $typeLabel;

    #[ORM\Column(type: Types::JSON)]
    #[Gedmo\Translatable]
    #[Gedmo\Versioned]
    private array $data = [];
    private array $simpleData = [];

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'user_id', onDelete: 'SET NULL')]
    private null|User $user = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'elements')]
    #[ORM\JoinTable(name: 'content_element_category')]
    #[ORM\JoinColumn(name: 'element_id')]
    #[ORM\InverseJoinColumn(name: 'category_id')]
    #[ORM\OrderBy(['left' => 'ASC'])]
    private Collection $categories;

    private bool $isCategories = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTime|null $publishedAt;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private \DateTime|null $unpublishedAt = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, mappedBy: 'elements')]
    private Collection $tags;

    #[ORM\Column]
    private int $position = 0;

    #[ORM\Column]
    private int $viewCount = 0;

    public function __construct()
    {
        $this->publishedAt = new \DateTime();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isPublic(): bool
    {
        return $this->public ?? false;
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;

        return $this;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getLocale(): string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return array|string|null
     */
    public function getData(string $name = null)
    {
        if ($name) {
            return $this->data[$name] ?? null;
        }

        return $this->data;
    }

    public function setData(array $data = null): self
    {
        $this->data = $data;

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(null|User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategories()
    {
        return $this->categories;
    }

    public function setCategories($categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getIsCategories()
    {
        return $this->isCategories;
    }

    public function isCategories(): bool
    {
        return $this->isCategories;
    }

    public function setIsCategories(bool $isCategories): self
    {
        $this->isCategories = $isCategories;

        return $this;
    }

    public function isAccessAuthenticated(): bool
    {
        if ($this->isCategories) {
            foreach ($this->categories as $category) {
                if ($category->isAccessAuthenticated()) {
                    return true;
                }
            }
        }

        return false;
    }

    public function getClassName(): string
    {
        return static::class;
    }

    public function getSimpleData(string $dataName = null)
    {
        return $dataName ? ($this->simpleData($dataName) ?? '') : $this->simpleData;
    }

    public function setSimpleData($simpleData)
    {
        $this->simpleData = $simpleData;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name.' ('.$this->type.')';
    }

    public function getTags()
    {
        return $this->tags;
    }

    public function setTags(ArrayCollection $tags)
    {
        $this->tags = $tags;

        return $this;
    }

    public function getTypeLabel()
    {
        return $this->typeLabel;
    }

    public function setTypeLabel(string $typeLabel)
    {
        $this->typeLabel = $typeLabel;

        return $this;
    }

    public function getContent()
    {
        return $this->data['content'] ?? $this->data['body'] ?? $this->data['description'] ?? '';
    }

    public function __call(string $name, array $arguments)
    {
        if (str_starts_with($name, 'set')) {
            $name = \lcfirst(substr($name, 3));
            $this->data[$name] = $arguments[0];
        }

        if (str_starts_with($name, 'get')) {
            $name = \lcfirst(substr($name, 3));
        }

        if (array_key_exists($name, $this->data)) {
            return $this->data[$name];
        }

        return null;
    }

    public function getPublishedAt(): \DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTime $publishedAt = null): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getUnpublishedAt()
    {
        return $this->unpublishedAt;
    }

    public function setUnpublishedAt(\DateTime $unpublishedAt = null): self
    {
        $this->unpublishedAt = $unpublishedAt;

        return $this;
    }

    public function getDraft(): bool
    {
        return $this->draft;
    }

    public function setDraft(bool $draft): self
    {
        $this->draft = $draft;

        return $this;
    }

    public function isDraft(): bool
    {
        return $this->draft ?? false;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getPosition(): int
    {
        return $this->position;
    }

    public function getViewCount(): int
    {
        return $this->viewCount ?? 0;
    }

    public function setViewCount(int $viewCount): self
    {
        $this->viewCount = $viewCount;

        return $this;
    }

    public function addView(): self
    {
        ++$this->viewCount;

        return $this;
    }
}

src/Controller/Admin/ElementController.php
<?php

namespace Tigris\ContentBundle\Controller\Admin;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\EventDispatcher\GenericEvent;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Tigris\BaseBundle\Form\ConfiguredForm\Type\ConfiguredFormType;
use Tigris\BaseBundle\Controller\Admin\BaseController;
use Tigris\BaseBundle\Controller\ChartControllerTrait;
use Tigris\BaseBundle\Form\Type\FormActionsType;
use Tigris\BaseBundle\Service\ArrayToFormService;
use Tigris\BaseBundle\Traits\FormTrait;
use Tigris\BaseBundle\Utils\Utils;
use Tigris\ContentBundle\Entity\Element;
use Tigris\ContentBundle\Event\Events;
use Tigris\ContentBundle\Form\Type\CreateElementType;
use Tigris\ContentBundle\Form\Type\ElementTranslationType;
use Tigris\ContentBundle\Form\Type\ElementType;
use Tigris\ContentBundle\Manager\ElementManager;
use Tigris\ContentBundle\Repository\ElementRepository;

#[Route('/admin/content/element')]
#[IsGranted('ROLE_ADMIN')]
class ElementController extends BaseController
{
    use FormTrait;
    use ChartControllerTrait;

    #[Route('/{type}', requirements: ['type' => '[a-zA-Z0-9\-_]+'])]
    public function index(Request $request, string $type): Response
    {
        $this->generateBreadcrumbs([
            'menu.content.elements' => ['route' => 'tigris_content_admin_element_index', 'params' => ['type' => $type]],
        ]);

        $elementTypes = $this->getParameter('tigris_content.elements');
        $allowTranslate = $this->getParameter('tigris_content.allow_translate');
        $locales = explode('|', $this->getParameter('app_locales'));
        $currentLocale = $this->getParameter('locale');
        $criteria = $this->getCriteria($request, 'adminContentElementCriteria');

        return $this->render('@TigrisContent/admin/element/index.html.twig', [
            'types' => $elementTypes,
            'type' => $elementTypes[$type],
            'typeName' => $type,
            'allowTranslate' => $allowTranslate,
            'locales' => $locales,
            'currentLocale' => $currentLocale,
            'criteria' => $criteria,
        ]);
    }

    #[Route('/{type}/data', requirements: ['type' => '[a-zA-Z0-9\-_]+'], options: ['expose' => 'admin'])]
    public function data(string $type, Request $request, ElementRepository $elementRepository): JsonResponse
    {
        $criteria = $this->getCriteria($request, 'adminContentElementCriteria');
        $filters = [
            'search' => $request->query->get('search', ''),
            'public' => $request->query->get('public', 1),
            'type' => $type,
        ];

        // Get data
        $data = $elementRepository->findData($criteria, $filters);

        return $this->paginatorToJsonResponse($data);
    }

    #[Route('/{type}/new', options: ['expose' => 'admin'], requirements: ['type' => '[a-zA-Z0-9\-_]+'])]
    public function new(Request $request, string $type, EventDispatcherInterface $eventDispatcher, EntityManagerInterface $em): Response
    {
        $this->generateBreadcrumbs([
            'menu.content.elements' => ['route' => 'tigris_content_admin_element_index', 'params' => ['type' => $type]],
            'content.element.add.add' => ['route' => 'tigris_content_admin_element_new', 'params' => ['type' => $type]],
        ]);

        $user = $this->getUser();

        $entity = (new Element())
            ->setUser($user)
            ->setPublic(false)
        ;

        if (null !== $type) {
            $entity->setType($type);
        }
        $form = $this->createForm(CreateElementType::class, $entity, [
            'action' => $this->generateUrl('tigris_content_admin_element_new', ['type' => $entity->getType()]),
            'attr' => ['no-ajax' => true],
        ]);
        $this->addFormActions(
            $form,
            $this->generateUrl('tigris_content_admin_element_index', ['type' => $entity->getType()]),
        );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($entity);
            $em->flush();

            $event = new GenericEvent($entity, ['backEnd' => true]);
            $eventDispatcher->dispatch($event, Events::CONTENT_ELEMENT_ADDED);

            $this->addFlash('success', 'content.element.add.success');

            return $this->redirectToRoute('tigris_content_admin_element_edit', ['id' => $entity->getId()]);
        }

        return $this->render('@TigrisContent/admin/element/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', requirements: ['id' => '\d+'], options: ['expose' => 'admin'], methods: ['GET', 'PUT'])]
    public function edit(
        Request $request,
        int $id,
        EventDispatcherInterface $eventDispatcher,
        ElementManager $elementManager,
        TranslatorInterface $translator,
        EntityManagerInterface $em
    ): Response {
        $entity = $elementManager->findOneById($id);
        $this->generateBreadcrumbs([
            'menu.content.elements' => ['route' => 'tigris_content_admin_element_index', 'params' => ['type' => $entity->getType()]],
            'content.element.edit.edit' => ['route' => 'tigris_content_admin_element_edit', 'params' => ['id' => $entity->getId()]],
        ]);

        $oldEntity = clone $entity;

        $elementTypes = $this->getParameter('tigris_content.elements');
        $form = $this->createForm(ElementType::class, $entity, [
            'method' => Request::METHOD_PUT,
        ]);
        $this->addFormActions(
            $form,
            $this->generateUrl('tigris_content_admin_element_index', ['type' => $entity->getType()]),
        );
        $form->add('data', ConfiguredFormType::class, [
            'fields' => $elementTypes[$entity->getType()]['fields'],
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($entity);
            $em->flush();
            $em->clear();

            $elementManager->includeExternalEntities($entity);

            $event = new GenericEvent($entity, ['backEnd' => true, 'oldEntity' => $oldEntity]);
            $eventDispatcher->dispatch($event, Events::CONTENT_ELEMENT_UPDATED);

            if ($request->isXmlHttpRequest()) {
                return new JsonResponse(['status' => 'success', 'message' => $translator->trans('content.element.edit.success')]);
            } else {
                $this->addFlash(
                    'success',
                    'content.element.edit.success'
                );

                return $this->redirectToRoute('tigris_content_admin_element_index', ['type' => $entity->getType()]);
            }
        }

        return $this->render('@TigrisContent/admin/element/edit.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/remove', requirements: ['id' => '\d+'], options: ['expose' => 'admin'], methods: ['GET', 'DELETE'])]
    public function remove(Request $request, Element $entity, EventDispatcherInterface $eventDispatcher, TranslatorInterface $translator, EntityManagerInterface $em): Response
    {
        $form = $this->getConfirmationForm(
            $this->generateUrl('tigris_content_admin_element_remove', ['id' => $entity->getId()]),
            $this->generateUrl('tigris_content_admin_element_index', ['type' => $entity->getType()])
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($entity);
            $em->flush();

            $event = new GenericEvent($entity, ['backEnd' => true]);
            $eventDispatcher->dispatch($event, Events::CONTENT_ELEMENT_DELETED);

            if ($request->isXmlHttpRequest()) {
                return new JsonResponse(['status' => 'success', 'message' => $translator->trans('content.element.delete.success')]);
            } else {
                $this->addFlash(
                    'success',
                    'content.element.delete.success'
                );

                return $this->redirectToRoute('tigris_content_admin_element_index', ['type' => $entity->getType()]);
            }
        }

        return $this->render('@TigrisContent/admin/element/remove.html.twig', [
            'form' => $form->createView(),
            'entity' => $entity,
        ]);
    }

    #[Route('/{id}/save', requirements: ['id' => '\d+'], options: ['expose' => 'admin'], methods: ['POST'])]
    public function save(Request $request, Element $entity, TranslatorInterface $translator, EntityManagerInterface $em): JsonResponse
    {
        $data = $request->request->all('data');
        if ([] === $data) {
            $entity->setData($data);
            $em->persist($entity);
            $em->flush();
        }

        return new JsonResponse(['message' => $translator->trans('content.element.save.success')]);
    }

    #[Route('/{id}/update-part', requirements: ['id' => '\d+'], options: ['expose' => 'admin'], methods: ['PUT'])]
    public function updatePart(Request $request, Element $entity, EventDispatcherInterface $eventDispatcher, ElementManager $elementManager, TranslatorInterface $translator, EntityManagerInterface $em): JsonResponse
    {
        $this->denyAccessUnlessGranted('edit', $entity);
        $data = $request->request->get('data', null);
        $value = $request->request->get('value', null);
        $oldEntity = clone $entity;

        if (!is_null($data) && !is_null($value)) {
            $method = 'set'.ucfirst($data);

templates/element/_list.html.twig
<div class="list">
{% block main %}
{% for entity in entities %}
{% block element %}
{{ entity.name }}
{% endblock %}
{% endfor %}

{% include '@TigrisBase/decorators/_pagination.html.twig' %}
{% endblock %}
</div>

templates/element/_show.html.twig
{% block element_content %}
{% endblock %}

templates/element/edit.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}

{% block title %} {{ parent() }} {% endblock %}

{% block main %}
{% block page_title %}<h1>{{ (entity.type ~ '.edit.edit')|trans }}</h1>{% endblock %}
{% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
{% endembed %}
{% endblock %}

templates/element/list.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}

{% block title %}{{ ("content.element.type." ~ type)|trans }} {{ parent() }} {% endblock %}

{% block main %}
<div class="list">
{% block content %}
{% for entity in entities %}
{% block element %}
{% endblock %}
{% endfor %}
{% endblock %}
</div>

{% endblock %}

templates/element/new.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}

{% block title %} {{ parent() }} {% endblock %}

{% block main %}
{% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
    {% block title %}<h1>{{ (entity.type ~ '.add.add')|trans }}</h1>{% endblock %}
{% endembed %}
{% endblock %}

templates/element/preview.html.twig
<article>

{% embed "@TigrisBase/decorators/_card.html.twig" %}
    {% block header %}
        <a href="{{ path('tigris_content_element_show', {'type' : entity.type, 'slug' : entity.slug}) }}">{{ entity.name }}</a>
        {% if is_granted('edit', entity) %}
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('tigris_content_admin_element_edit', {'id' : entity.id})}}" class="btn btn-light float-right">{{ '.icon-pencil-alt'|parse_icons }}</a>
        {% else %}
            <a href="{{ path('tigris_content_element_edit', {'id' : entity.id})}}" class="btn btn-light float-right">{{ '.icon-pencil-alt'|parse_icons }}</a>
        {% endif %}       
        {% endif %}
    {% endblock %}

    {% block body %}
    {% if entity.image is not empty %}<img src="{{ asset(entity.image.webPath) }}" />{% endif %}
        {{ entity.content|raw }}
        {% if bundle_exists('TigrisSocialBundle') and socialTools[entity.id] is defined  %}
        {% include '@TigrisSocial/reaction/_buttons.html.twig' ignore missing with {'social' : socialTools[entity.id], 'entityId': entity.id, 'entityName': entity.className} %}
        {% endif %}
    {% endblock %}
{% endembed %}
</article>

templates/element/remove.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}
{% block main %}
    {% embed '@TigrisBase/decorators/_form.html.twig' with {'class': ''} %}
        {% block title %}{{ 'content.element.delete.delete'|trans }}{% endblock %}
        {% block body %}
        <p>{{ 'content.element.delete.message'|trans({'%entity%': entity.name})|raw }}</p>
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/element/show.html.twig
{% extends app.request.xmlHttpRequest 
        ? '@TigrisBase/ajax-layout.html.twig'
        : '@TigrisBase/layout.html.twig' %}

{% block title %}{{ entity.name }} - {{ parent() }} {% endblock %}

{% block main %}
<div class="element {{ entity.type }}" id="{{ entity.type }}-{{ entity.slug }}">

{% if edit %}
<tigris-content-editor id="content-editor" route="tigris_content_admin_element_save" :element-id.number="{{ entity.id }}" :data="{{ entity.simpleData|json_encode }}" v-slot="{content}">
<div>
<div class="wysiwyg-toolbar">   
</div>
{% endif %}
<div class="clearfix">
{% block element_content %}
{% endblock %}
</div>
{% if edit %}
</div>
</tigris-content-editor>
{% endif %}
</div>
{% endblock %}

templates/element/user_list.html.twig
{% extends '@TigrisBase/user/my_account_layout.html.twig' %}

{% block content %}
<h1>
{% if types|length == 1 %}
{{ ((types|keys|first) ~ '.list')|trans }}
{% else %}
{{ 'content.element.list'|trans }}
{% endif %}
</h1>
<tigris-data-list route="tigris_content_element_userdata" :init-filters='{"search":"", "type":"", "public":""}' v-slot="{loadData, entities, filters, totalCount, begin, end, sort}">
{% embed '@TigrisBase/decorators/_card.html.twig' with {'class': ''} %}
    {% block header %}
        {% if types|length == 1 %}
        <button-action v-on:formsaved="loadData()" route="tigris_content_element_new" :modal="true" :route-params="{type: '{{ types|keys|first }}'}" type="success">
            <span class="btn-label">{{ '.icon-plus'|parse_icons }}</span> {{ ((types|keys|first) ~ '.add.add')|trans }}
        </button-action>
        {% else %}
        <div class="btn-group dropdown" role="group">
            <button id="btn-add-element" type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ '.icon-plus'|parse_icons }}</span> {{ 'content.element.add.add'|trans }}
            </button>
            <div class="dropdown-menu" aria-labelledby="btn-add-element">
            {% for name, type in types %}
            <button-action v-on:formsaved="loadData()" route="tigris_content_element_new" :modal="true" :route-params="{type: '{{ name }}'}" class="dropdown-item">
                {{ ('content.element.type.' ~ name)|trans }}
            </button-action>
            {% endfor %}
            </div>
        </div>
        {% endif %}

    {% endblock %}
    {% block body %}
    <div class="hstack flex-wrap">
        {% if types|length > 1 %}
    
        <div class="form-group">
            <label class="form-label"><small>{{ 'content.element.type.type'|trans }}</small></label>
            <select class="form-control" v-model="filters.type">
                <option value="">{{ 'content.element.type.all'|trans }}</option>
                {% for key, type in types %}
                <option value="{{ key }}">{{ (type.name)|trans }}</option>
                {% endfor %}
            </select>
        </div>
        {% endif %}

        <div class="form-group ms-2">
            <label class="form-label"><small>{{ 'content.element.status.label'|trans }}</small></label>
            <select class="form-control" v-model="filters.public">
                <option value="">{{ 'content.element.status.all'|trans }}</option>
                <option value="1">{{ 'content.element.status.public'|trans }}</option>
                <option value="0">{{ 'content.element.status.non_public'|trans }}</option>
            </select>
        </div>

        <div class="form-group ms-2">
            <label class="form-label"><small>{{ 'content.element.search'|trans }}</small></label>
            <div class="input-group ">
                <span class="input-group-text">{{ '.icon-search'|parse_icons }}</span>
                <input type="text" class="form-control" v-model="filters.search"/>
            </div>
        </div>

        <div class="ms-auto d-none d-md-block">
            <div class="form-group">
                <label><small>{{ 'results_per_page'|trans }}</small></label>
                <item-count-select></item-count-select>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block table %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th><sort-item label="{{ 'name'|trans }}" value="name" v-on:change="sort"></sort-item></th>
                <th class="d-none d-lg-table-cell"><sort-item label="{{ 'content.element.createdAt'|trans }}" value="createdAt" v-on:change="sort"></sort-item></th>
                <th class="d-none d-lg-table-cell"><sort-item label="{{ 'content.element.updatedAt'|trans }}" value="updatedAt" v-on:change="sort"></sort-item></th>
                {#<th><sort-item label="{{ 'content.element.publishedAt'|trans }}" value="publishedAt" v-on:change="sort"></sort-item></th>#}
                <th><sort-item label="{{ 'content.element.status.public'|trans }}" value="public" v-on:change="sort"></sort-item></th>
                {% if types|length > 1 %}<th><sort-item label="{{ 'content.element.type.type'|trans }}" value="type" v-on:change="sort"></sort-item></th>{% endif %}
                <th width="120px">{{ 'actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="entity in entities" :key="entity.id">
                <td><b>${ entity.name }</b></td>
                <td class="d-none d-lg-table-cell">${ $filters.formatDate(entity.createdAt, 'L') }</td>
                <td class="d-none d-lg-table-cell">
                    <span v-show="entity.updatedAt != entity.createdAt">${ $filters.formatDate(entity.updatedAt, 'L') }</span>
                    <span v-show="entity.updatedAt == entity.createdAt">-</span>
                </td>
                {#<td>${ entity.publishedAt | formatDate }</td>#}
                <td>
                    <span class="badge bg-danger" v-if="!entity.public">{{ 'no'|trans }}</span>
                    <span class="badge bg-success" v-if="entity.public">{{ 'yes'|trans }}</span>
                </td>
                {% if types|length > 1 %}
                <td>${entity.typeLabel}</td>
                {% endif %}
                <td>
                    <div class="btn-group btn-group-sm">
                        <button-action v-on:formsaved="loadData()" route="tigris_content_element_show_id" :route-params="{id:entity.id, type:entity.type}" type="primary" target="_blank">{{ '.icon-eye'|parse_icons }}</button-action>
                        <button-action v-on:formsaved="loadData()" route="tigris_content_element_edit" :route-params="{id:entity.id}" type="secondary">{{ '.icon-pencil-alt'|parse_icons }}</button-action>
                        <button-action v-on:formsaved="loadData()" route="tigris_content_element_remove" :modal="true" :route-params="{id:entity.id}" type="danger" v-if="!entity.public">{{ '.icon-trash'|parse_icons }}</button-action>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    {% endblock %}
    {% block footer %}
    <div class="data-list-footer">
        <em>{{ 'data_count'|trans({'%begin%':'${begin}', '%end%':'${end}', '%total%':'${totalCount}'}) }}</em>
        <pagination></pagination>
    </div>
    {% endblock %}
{% endembed %}
</tigris-data-list>
{% endblock %}